Repository quality-match/hari-client, pull requests merged in 2024-10, with the labels that each got.

#19 Km/hari client/apply feedback
  docs/example_code/quickstart.py
  hari_client/client/client.py
  hari_client/client/errors.py
  hari_client/models/models.py
  hari_client/upload/hari_uploader.py
  tests/test_parse_response_model.py
Labels: cleanup

#17 add attribute upload
  CHANGELOG.md
  docs/example_code/quickstart.py
  hari_client/client/client.py
  hari_client/models/models.py
  hari_client/upload/hari_uploader.py
  tests/test_hari_uploader.py
Labels: enhancement

#31 Fix update attribute request
  hari_client/client/client.py
Labels: bug

#30 Clean up of uuid vs str inconsistencies in current client api models
  docs/example_code/quickstart.py
  hari_client/models/models.py
  hari_client/upload/hari_uploader.py
  tests/test_hari_uploader.py
Labels: cleanup

#32 fix `HARIClient.create_attribute` method
  hari_client/client/client.py
Labels: bug
